SCHEMA : COLLEGEADMISSIONSYSTEM
TABLE : APPLICATION


INSERT INTO COLLEGEADMISSIONSYSTEM.APPLICATION
(APPLICATION_ID, STATUS, ADMIN_ID, PROGRAM_ID, SID)
VALUES('a11', 'APPROVED', 92, 1, 1);
INSERT INTO COLLEGEADMISSIONSYSTEM.APPLICATION
(APPLICATION_ID, STATUS, ADMIN_ID, PROGRAM_ID, SID)
VALUES('a12', 'applied', 91, 62, 2);
INSERT INTO COLLEGEADMISSIONSYSTEM.APPLICATION
(APPLICATION_ID, STATUS, ADMIN_ID, PROGRAM_ID, SID)
VALUES('a13', 'APPROVE', 92, 62, 3);





TABLE : COLLEGEADMIN


INSERT INTO COLLEGEADMISSIONSYSTEM.COLLEGEADMIN
(ADMIN_ID, STATUS, SID)
VALUES(91, 'approve', 1);
INSERT INTO COLLEGEADMISSIONSYSTEM.COLLEGEADMIN
(ADMIN_ID, STATUS, SID)
VALUES(92, 'reject', 2);




TABLE : PROGRAM


INSERT INTO COLLEGEADMISSIONSYSTEM.PROGRAM
(PROGRAM_ID, DEPARTMENT, PROGRAM)
VALUES(1, 'cse', 'btech');
INSERT INTO COLLEGEADMISSIONSYSTEM.PROGRAM
(PROGRAM_ID, DEPARTMENT, PROGRAM)
VALUES(62, 'ece', 'btech');



TABLE : STUDENT

INSERT INTO COLLEGEADMISSIONSYSTEM.STUDENT
(SID, EMAIL, SNAME)
VALUES(1, 'priyanka@gmail.com', 'priyanka');
INSERT INTO COLLEGEADMISSIONSYSTEM.STUDENT
(SID, EMAIL, SNAME)
VALUES(2, 'nhitha@gmail.com', 'nihitha');
INSERT INTO COLLEGEADMISSIONSYSTEM.STUDENT
(SID, EMAIL, SNAME)
VALUES(3, 'dhanush@gmail.com', 'dhanush');





